# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 800eb8dfdb4c0786d6a4195a6a705ab7eae3cb156a28e94babb190f75ce0a9f42ad1a0f41ee9f0c28bfae6c9e446034eea9bfa3ac4db03d527f3a16225f43068

test:
  secret_key_base: 53a7769761ae2c8d359c3927e06b52bd05c6328488dd8999cf4500e4422b5415f6933d732a192714eae0fef927d785ba48907743656ff528caaedd74c9f6204d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
